### PR TITLE
Fix `previewFeaturesEnabled` (from `previewFeaturesEnableds`)

### LINKED ISSUE #800: pulumi-terraform-bridge has generated `preview_features_enableds` instead of `preview_features_enabled`
### Describe what happened

In this PR https://github.com/pulumi/pulumi-snowflake/pull/777, it seems pulumi-terraform-bridge has generated a provider configuration setting with an extra `s` (plural?)
`preview_features_enableds` instead of `preview_features_enabled`

At least, that is my understanding of what happened, so it might be a bug in `pulumi-terraform-bridge`, but I'm not sure, so I'm opening an issue here for now.

In addition, the setting (and maybe other settings) are missing from the doc here https://www.pulumi.com/registry/packages/snowflake/

I can also add that it's confusing to know which is the exact setting name, it's actually `snowflake:previewFeaturesEnableds`, snake case doesn't work, but it works for `account_name` and the message is not accurate as using `snowflake:preview_features_enableds` results with:

```
  pulumi:providers:snowflake (default_1_0_1):
    error: pulumi:providers:snowflake resource 'default_1_0_1' has a problem: `snowflake:previewFeaturesEnableds` is not a valid configuration key for the snowflake provider. If the referenced key is not intended for the provider, please choose a different namespace from `snowflake:`.
```

using `snowflake:preview_features_enabled` or `snowflake:previewFeaturesEnabled` results with:
```
Diagnostics:
  pulumi:providers:snowflake (default_1_0_1):
    error: pulumi:providers:snowflake resource 'default_1_0_1' has a problem: could not validate provider configuration: Attribute must be a list. Check `pulumi config get snowflake:previewFeaturesEnableds`.
```

eventually, using `snowflake:previewFeaturesEnableds` works

The behaviour is also different when defining an explicit provider instance where the actual setting must be in snake_case `preview_features_enableds`, camelCase fails.

### Sample program

```yaml
# pulumi.Prod.yaml
config:
  snowflake:organization_name: my-org
  snowflake:account_name: my-account
  snowflake:authenticator: SNOWFLAKE_JWT
  snowflake:privateKey: somekey
  snowflake:role: ACCOUNTADMIN
  snowflake:user: "SVCACCT_PULUMI"
  snowflake:previewFeaturesEnabled: # or snowflake:preview_features_enabled or # snowflake:preview_features_enableds
    - snowflake_network_policy_attachment_resource
```

### Log output

```
  pulumi:providers:snowflake (default_1_0_1):
    error: pulumi:providers:snowflake resource 'default_1_0_1' has a problem: could not validate provider configuration: Attribute must be a list. Check `pulumi config get snowflake:previewFeaturesEnableds`.
```

or 
```
  pulumi:providers:snowflake (default_1_0_1):
    error: pulumi:providers:snowflake resource 'default_1_0_1' has a problem: `snowflake:previewFeaturesEnableds` is not a valid configuration key for the snowflake provider. If the referenced key is not intended for the provider, please choose a different namespace from `snowflake:`.
```

### Affected Resource(s)

Provider settings

### Output of `pulumi about`

```
> pulumi about
CLI          
Version      3.145.0
Go Version   go1.23.4
Go Compiler  gc

Plugins
KIND      NAME       VERSION
language  python     3.145.0
resource  snowflake  1.0.1

Host     
OS       darwin
Version  15.2
Arch     arm64
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #800

### CODE REVIEW

File: provider/resources.go [hunk 1]
```diff
@@ -60,27 +60,18 @@ func Provider() info.Provider {
...
-			},
-			"protocol": {
-				Default: &info.Default{EnvVars: []string{"SNOWFLAKE_PROTOCOL"}},
-			},
-			"warehouse": {
-				Default: &info.Default{EnvVars: []string{"SNOWFLAKE_WAREHOUSE"}},
-			},
+			// Fix pluralization.
+			//
+			// Previously was "previewFeaturesEnableds".
```
Comment (t0yv0) [inline provider/resources.go:65]: Oof.

**Review by t0yv0 — APPROVED** [review]

**Review by guineveresaenger — APPROVED** [review]
